### PR TITLE
implode|prune: support --yes

### LINKED ISSUE #982: --yes flag is not working properly
**Describe the bug**
Hello and thanks for amazing tool. I enjoy it a lot. 

I wanted to report an issue I encountered while using  rtx prune.

According to the help page of `rtx prune` 

  -y, --yes
          Answer yes to all prompts

However, `rtx prune --yes` is asking for confirmation and waiting user input.

**To Reproduce**
1. Install a unused version of tool.
2. run `rtx prune --yes`
3. see it is waiting for user input with asking : `remove java@21.0.1 ? [y/n]`

**Expected behavior**
I would expect when `--yes` flag is passed user input should not be waited and operation should proceed.

**`rtx doctor` output**

```
➜ rtx doctor
rtx version:
  2023.11.1 macos-arm64 (2023-11-08)

build:
  Target: aarch64-apple-darwin
  Features: BREW, DEFAULT, NATIVE_TLS
  Built: Wed, 8 Nov 2023 02:41:46 +0000
  Rust Version: rustc 1.72.1 (d5c2e9c34 2023-09-13) (Homebrew)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin23.0)

rtx data directory:
  /Users/zahidkizmaz/.local/share/rtx

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false", "yes": "false"}

config files:
  /Users/zahidkizmaz/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  poetry   https://github.com/rtx-plugins/rtx-poetry.git#3d4c703
  python   (core)
  ruby     (core)

toolset:
  go@latest, node@lts, python@latest

No problems found
```

Thank you for your consideration and for maintaining this open source project. It is greatly appreciated.

Regards

### PR DESCRIPTION
**Pull request by jdx**
Fixes #982

### CODE REVIEW

File: src/cli/implode.rs [hunk 1]
```diff
@@ -33,20 +34,32 @@ impl Command for Implode {
                 rtxprintln!(out, "rm -rf {}", f.display());
             }
 
-            if f.is_dir() {
-                if !self.dry_run && prompt::confirm(&format!("remove {} ?", f.display()))? {
+            if self.confirm_remove(&config, f)? {
+                if f.is_dir() {
                     remove_all(f)?;
-                    return Ok(());
```
Comment (jdx) [inline src/cli/implode.rs:39]: this straight up looks like a bug
