### PR TITLE
fix: Always return a list on 'rtx ls <plugin> --json'

### LINKED ISSUE #882: Let `rtx ls --json` always return an array
A tool is installed, it returns an array:
```
# rtx ls vault --current --json
[
  {
    "version": "1.14.2",
    "requested_version": "1.14.2",
    "install_path": "/home/patrick/.local/share/rtx/installs/vault/1.14.2",
    "source": {
      "type": ".tool-versions",
      "path": "/home/patrick/.tool-versions"
    }
  }
]
```

When a tool isn't, it returns an object:
```
# rtx ls tflint --current --json
{}
```

That makes the output json hard to process with other tools like jq.
Always returning an array would help with that.

### PR DESCRIPTION
**Pull request by booniepepper**
closes #882

### CODE REVIEW

File: src/cli/ls.rs [hunk 1]
```diff
@@ -273,6 +271,19 @@ impl Ls {
 
 type RuntimeRow = (Arc<Tool>, ToolVersion, Option<ToolSource>);
 
+impl From<RuntimeRow> for JSONToolVersion {
```
Comment (jdx) [inline src/cli/ls.rs:274]: so clean!
